server:
  port: 80
spring:
  application: # 配置应用信息
    name: hong.dept.consumer   # 配置应用名称
  cloud: # cloud配置
    nacos: # nacos 配置
      discovery: # 服务发现
        service: ${spring.application.name} # 使用微服务的名称作为注册的服务名称
        server-addr: nacos-server:8848  # nacos 的注册注册地址
        namespace: 37bc85e2-0f3b-4849-a8d6-172584b62c41
        group: HONG_GROUP
        # 配置集群名称
        cluster-name: HongCluster
        username: hong
        password: hong
        metadata: # 配置元数据项
          version: 1.0 # 自定义元数据项
          company: zhangdehong
          url: www.henley.com
          author: zhangdehong
          register-enabled: false  #消费端不注册

ribbon:
  eager-load:
    clients: hong.dept.consumer
    enabled: true  # 采用饿汉式