server:
  # 端口
  port: 8003
mybatis-plus:
  # 别名
  type-aliases-package: com.hong.provider.vo
spring:
  application: # 配置应用信息
    name: hong.dept.provider   # 配置应用名称
  cloud: # cloud配置
    nacos: # nacos 配置
      discovery: # 服务发现
        service: ${spring.application.name} # 使用微服务的名称作为注册的服务名称
        server-addr: nacos-server:8848  # nacos 的注册注册地址
        namespace: 37bc85e2-0f3b-4849-a8d6-172584b62c41
        group: HONG_GROUP
        # 配置集群名称
        cluster-name: HongCluster
        username: hong
        password: hong
        metadata: # 配置元数据项
          version: 1.0 #自定义元数据项
          company: zhangdehong
          url: www.henley.com
          author: zhangdehong
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/alibaba-cloud-8003
    username: root
    password: hong#0618
    dynamic:
      druid:
        initial-size: 5
        # 维持最小连接池大小
        min-idle: 10
        # 最大连接池大小
        max-active: 50
        # 最大等待时间
        max-wait: 60000
        # 关闭空闲链接时间间隔
        time-between-eviction-runs-millis: 60000
        # 链接最小生存时间
        min-evictable-idle-time-millis: 30000
        # 状态监测
        validation-query: SELECT 1 FROM dual
        # 空闲时检测链接是否有效
        test-while-idle: true
        # 申请连接时检测是否有效
        test-on-borrow: false
        # 归还时检测链接是否有效
        test-on-return: false
        # psCache缓存
        pool-prepared-statements: false
        # 配置ps缓存
        max-pool-prepared-statement-per-connection-size: 20
        # 开启过滤
        filters: stat, wall, slf4j
        # 配置监控页面
        stat-view-servlet:
          # 启用Druid监控配置
          enabled: true
          # 访问白名单
          allow: 127.0.0.1
          login-username: hong
          login-password: hong
          # 允许重置
          reset-enabled: true
          # 访问路径
          url-pattern: /druid/*
        web-stat-filter:
          # 启用url监控
          enabled: true
          # 跟踪全部服务
          url-pattern: /*
          exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
        filter:
          slf4j:
            enabled: true
            # 启用数据库日志
            data-source-log-enabled: true
            # 启用执行日志
            statement-executable-sql-log-enable: true
          stat:
            # 合并统计
            merge-sql: true
            # 慢执行SQL
            log-slow-sql: true
            # 慢SQL执行时间
            slow-sql-millis: 1
          wall:
            enabled: true
            config:
              # 允许批量执行SQL
              multi-statement-allow: true
              # 禁止删除语句
              delete-allow: false
        aop-patterns: "com.hong.provider.controller.*,com.hong.provider.service.*,com.hong.provider.dao"
